// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhtvxziachtotvtjxsgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodHZ4emlhY2h0b3R2dGp4c2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTgwNDgsImV4cCI6MjA3MzA3NDA0OH0.o0BfPTD6a97EHPebkWSLZCIiCJNRVrWpYzvT3cowbSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});